name: CI/CD with Rsync

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: webactions

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          # Add any build commands here if required
          # For example, if you use a static site generator:
          # npm install
          # npm run build

      - name: Deploy to Server
        uses: appleboy/rsync-action@master
        with:
          args: -avz --delete --exclude '.git' --exclude '.github' --exclude 'node_modules' ${{ github.workspace }}/* username@your-server:/path/to/destination
