name: Deploy to Web Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Web Server
        run: sudo rsync -avz /home/anas/actions-runner/web1/gitaction/gitaction /var/www/html/

