name: CI/CD with Rsync

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: webactions
  steps:
     - name: Deploy to Server
        uses: gitaction/rsync-action@v2
        with:
          args: -avz --delete --exclude '.git' --exclude '.github' --exclude 'node_modules' ${{ github.workspace }}/* ./:/var/www/html
